# Generated by Django 6.0.3 on 2026-03-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produto_categoria_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='dimensoes',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
